### ISSUE TITLE
bump jekyll version suported

### ISSUE THREAD

**Issue by matheuseduardo** [aterenin/minima-reboot#3]
It's a **really good work**, but I can't run now because on my jekyll cause is requesting a "old" version of jekyll (3.6).

I think you could upgrade dependency file (minima-reboot.gemspec) to match new versions of jekyll.

best regards!

**Comment by aterenin** [comment]
Could you try running it on newer Jekyll, and if nothing is broken, make a PR? I would expect everything will just work and am happy to just bump the version number in that case. 

If not, I still use this package myself, and would be happy to know what needs to be fixed.

**Comment by aterenin** [comment]
Updated in #4.
